version: "3"

services:
  mariadb:
    image: mariadb:latest
    restart: always
    ports:
      - 3307:3306
    volumes:
      - dbvolume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

volumes:
  dbvolume:
